import type { Product, Collection } from './types';

export const collections: Collection[] = [
  { id: 'classic-elegance', name: { en: 'Classic Elegance', tr: 'Klasik Zarafet', ar: 'الأناقة الكلاسيكية' } },
  { id: 'urban-explorer', name: { en: 'Urban Explorer', tr: 'Şehir Kaşifi', ar: 'مستكشف المدينة' } },
  { id: 'seasonal-vibes', name: { en: 'Seasonal Vibes', tr: 'Mevsimsel Esintiler', ar: 'أجواء موسمية' } },
];

export const products: Product[] = [
  {
    id: 'p1',
    name: { en: 'Elegant Summer Dress', tr: 'Zarif Yazlık Elbise', ar: 'فستان صيفي أنيق' },
    description: {
      en: 'A light and airy summer dress, perfect for warm days and evening strolls.',
      tr: 'Sıcak günler ve akşam yürüyüşleri için mükemmel, hafif ve havadar bir yazlık elbise.',
      ar: 'فستان صيفي خفيف ومتجدد الهواء، مثالي للأيام الدافئة والنزهات المسائية.',
    },
    images: ['https://picsum.photos/seed/101/600/800'],
    status: 'available',
    season: 'summer',
    type: 'dress',
    collection: 'seasonal-vibes',
    model: 'M-001',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    price: 120,
  },
  {
    id: 'p2',
    name: { en: "Men's Winter Coat", tr: 'Erkek Kışlık Mont', ar: 'معطف شتوي رجالي' },
    description: {
      en: 'A warm and stylish coat to keep you comfortable during the cold winter months.',
      tr: 'Soğuk kış aylarında sizi rahat ettirecek sıcak ve şık bir mont.',
      ar: 'معطف دافئ وأنيق لتبقيك مرتاحًا خلال أشهر الشتاء الباردة.',
    },
    images: ['https://picsum.photos/seed/102/600/800'],
    status: 'available',
    season: 'winter',
    type: 'coat',
    collection: 'urban-explorer',
    model: 'M-002',
    price: 250,
  },
  {
    id: 'p3',
    name: { en: 'Stylish Autumn Jacket', tr: 'Şık Sonbahar Ceketi', ar: 'جاكيت خريفي أنيق' },
    description: {
      en: 'A versatile jacket that is perfect for the changing weather of autumn.',
      tr: 'Sonbaharın değişken havaları için mükemmel olan çok yönlü bir ceket.',
      ar: 'جاكيت متعدد الاستخدامات مثالي لطقس الخريف المتغير.',
    },
    images: ['https://picsum.photos/seed/103/600/800'],
    status: 'sold_out',
    season: 'autumn',
    type: 'jacket',
    collection: 'urban-explorer',
    model: 'M-003',
    price: 180,
  },
  {
    id: 'p4',
    name: { en: 'Casual Spring T-Shirt', tr: 'Rahat Baharlık Tişört', ar: 'تي شيرت ربيعي كاجوال' },
    description: {
      en: 'A comfortable and breathable t-shirt for a fresh spring look.',
      tr: 'Taze bir bahar görünümü için rahat ve nefes alabilen bir tişört.',
      ar: 'تي شيرت مريح وقابل للتنفس لإطلالة ربيعية منعشة.',
    },
    images: ['https://picsum.photos/seed/104/600/800'],
    status: 'available',
    season: 'spring',
    type: 't-shirt',
    collection: 'seasonal-vibes',
    model: 'M-004',
    price: 45,
  },
  {
    id: 'p5',
    name: { en: 'Formal Evening Gown', tr: 'Resmi Abiye Elbise', ar: 'فستان سهرة رسمي' },
    description: {
      en: 'A stunning gown for special occasions, designed to make a statement.',
      tr: 'Özel günler için tasarlanmış, dikkat çekici, büyüleyici bir abiye.',
      ar: 'فستان مذهل للمناسبات الخاصة، مصمم لترك انطباع.',
    },
    images: ['https://picsum.photos/seed/105/600/800'],
    status: 'available',
    season: 'winter',
    type: 'gown',
    collection: 'classic-elegance',
    model: 'M-005',
    price: 450,
  },
  {
    id: 'p6',
    name: { en: 'Comfortable Denim Jeans', tr: 'Rahat Kot Pantolon', ar: 'جينز مريح' },
    description: {
      en: 'Classic denim jeans that offer both comfort and timeless style.',
      tr: 'Hem rahatlık hem de zamansız stil sunan klasik kot pantolon.',
      ar: 'جينز كلاسيكي يوفر الراحة والأناقة الخالدة.',
    },
    images: ['https://picsum.photos/seed/106/600/800'],
    status: 'available',
    season: 'autumn',
    type: 'jeans',
    collection: 'urban-explorer',
    model: 'M-006',
    videoUrl: 'https://www.youtube.com/embed/videoseries?list=PLx0sYbCqOb8TBPRdmp0c-yD2o_rMym86X',
    price: 90,
  },
];
